[api]
  api_port = 8099
  forwarder_port = 8090
  timeout = 45

[log]
  # Discard means not write log to local file
  file_name = "Discard"
  level = "info"
  standard_log_version = "1"
  access_log_version = "1"
  formatter = "json"
  kafka_enabled = true

[kafka]
  access_log_topic = "forwarder_access"
  standard_log_topic = "forwarder_api"
  hosts = "10.10.42.14:9092;10.10.42.15:9092;10.10.42.16:9092;10.10.42.17:9092;10.10.42.18:9092;10.10.42.19:9092"
  # map to Linger in code
  flush_frequency = 100
  max_connections = 5
  max_connections_per_broker = 5
  batch_size = 16384
  max_requests = 10
  send_routines = 10
  receive_routines = 10
  # 0 = NoResponse, 1 = WaitForLocal, -1 = WaitForAll, default is 1
  required_acks = 0
  queue_length = 1024
  # Unit is Millisecond
  enqueue_timeout = 1000

[jaeger]
  host = "tpe-jaeger-agent.tyd.svc.cluster.local"
  port = 6831
  sample_rate = 0.1
  queue_size = 128
  flush_interval = "60s"

[database]
[database.mgo.default]
  name = "Mgo"
  user = "geoman"
  password = "wM7DJRQN81WxX4zD"
  authdatabase = "admin"
  max_conn = 10
  max_idle = 15
  host_num = 3
  timeout = 30
  sharduser= "sharder"
  shardpassword = "izihGm5UD7KZnCRzbAkFX6PLdtUXK7n3"
  direct = false

[database.mgo.instance.0]
  host = "10.10.40.42"
  port = 7379
  enabled = true

[database.mgo.instance.1]
  host = "10.10.40.48"
  port = 7379
  enabled = true

[database.mgo.instance.2]
  host = "10.10.40.49"
  port = 7379
  enabled = true


